// <auto-generated />
using System;
using HouseholdPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseholdPlanner.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20260324084625_InitialFullSchema")]
    partial class InitialFullSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.AvailabilitySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndLocalTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartLocalTime")
                        .HasColumnType("time");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("availability_slots", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("meals", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("meal_plans", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.MealTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("meal_tags", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.MealTagMap", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("MealTagId")
                        .HasColumnType("integer");

                    b.HasKey("MealId", "MealTagId");

                    b.HasIndex("MealTagId");

                    b.ToTable("meal_tag_maps", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.PlannerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.ToTable("tasks", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.Subtask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlannerTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlannerTaskId");

                    b.ToTable("subtasks", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.TaskSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("AmountOfTime")
                        .HasColumnType("interval");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("StartLocalTime")
                        .HasColumnType("time");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("task_schedules", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("HouseholdPlanner.Data.Entities.User", "User")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.MealPlan", b =>
                {
                    b.HasOne("HouseholdPlanner.Data.Entities.Meal", "Meal")
                        .WithMany("MealPlans")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.MealTagMap", b =>
                {
                    b.HasOne("HouseholdPlanner.Data.Entities.Meal", "Meal")
                        .WithMany("MealTagMappings")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseholdPlanner.Data.Entities.MealTag", "MealTag")
                        .WithMany("MealTagMappings")
                        .HasForeignKey("MealTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("MealTag");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.PlannerTask", b =>
                {
                    b.HasOne("HouseholdPlanner.Data.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.Subtask", b =>
                {
                    b.HasOne("HouseholdPlanner.Data.Entities.PlannerTask", "PlannerTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("PlannerTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlannerTask");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.TaskSchedule", b =>
                {
                    b.HasOne("HouseholdPlanner.Data.Entities.PlannerTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseholdPlanner.Data.Entities.User", "User")
                        .WithMany("TaskSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.Meal", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("MealTagMappings");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.MealTag", b =>
                {
                    b.Navigation("MealTagMappings");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.PlannerTask", b =>
                {
                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("HouseholdPlanner.Data.Entities.User", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("TaskSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
